### ISSUE TITLE
Revisit process for merging multiple pull requests

### ISSUE THREAD

**Issue by tXiao95** [brianconroy/preferential_surveillance#5]
Thanks for merging my PR's! It's pretty satisfying when I get the notification haha.

However, I think we need to reconsider some parts of our PR review process. Right now the commit history is a little hard to read. 

![image](https://user-images.githubusercontent.com/10318610/88260374-3da90500-cc92-11ea-9774-6466c3a004fe.png)

Ideally we would want a straight line and loops that don't overlap each other. In Git terms, this visual means that we want PR's to branch off of the previously accepted one, rather than all branching off from the same initial commit, even after the master branch merges certain PR's first. So ideally, you'd first merge PR#1. Then, I would rebase where PR#2 branches off the master branch to start from the merge commit for PR#1. Only after the rebase, then you would merge PR#2. If you merge PR#2 after merging PR#1 and I haven't yet rebased, then we'll get the overlapping loops. Allowing for the rebasing would give us the more linear, cleaner commit history. 

This was able to happen without any issues from Git because each PR worked on a completely different set of files. I imagine in the future if I submit multiple PR's I might change the same files, in which case you would not be able to just merge the two PR's in succession without me resolving merge conflicts on my end first. 

But for now, for any PR's, I think we will need to accept them one at a time. Once you accept a single PR, you can notify me (or I'll receive an email anyway) and you can request that I rebase the other PR's  on the latest merge commit. I would basically do steps 7-11 from this [example workflow](https://github.com/servo/servo/wiki/Github-workflow). This will help keep things organized better. Let me know what you think or if none of this makes sense and we can talk more about it.

**Comment by tXiao95** [comment]
Actually now that I've thought about it a bit, I think this is fine. If I disregard the purple feature that changed nothing, the other two PR's are fine. If a merge is allowed to happen, then so be it. I don't think it's really that much of a concern, rebasing was mostly just an aesthetic thing.

**Comment by brianconroy** [comment]
Sorry for the late reply on this - has been a crazy end of the week :( Just getting caught up on things. Going forward I agree with the intent to make the commit history as clean as possible. I think that's a fine policy to merge, notify, and rebase in the case of multiple PRs.
